/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedResearchRouteImport } from './routes/_authenticated/research'
import { Route as AuthenticatedPlannerRouteImport } from './routes/_authenticated/planner'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedResearchIndexRouteImport } from './routes/_authenticated/research.index'
import { Route as AuthenticatedPlannerIndexRouteImport } from './routes/_authenticated/planner.index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedResearchReportIdRouteImport } from './routes/_authenticated/research.$reportId'
import { Route as AuthenticatedPlannerPlanIdRouteImport } from './routes/_authenticated/planner.$planId'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResearchRoute = AuthenticatedResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerRoute = AuthenticatedPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResearchIndexRoute =
  AuthenticatedResearchIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedResearchRoute,
  } as any)
const AuthenticatedPlannerIndexRoute =
  AuthenticatedPlannerIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedResearchReportIdRoute =
  AuthenticatedResearchReportIdRouteImport.update({
    id: '/$reportId',
    path: '/$reportId',
    getParentRoute: () => AuthenticatedResearchRoute,
  } as any)
const AuthenticatedPlannerPlanIdRoute =
  AuthenticatedPlannerPlanIdRouteImport.update({
    id: '/$planId',
    path: '/$planId',
    getParentRoute: () => AuthenticatedPlannerRoute,
  } as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/planner': typeof AuthenticatedPlannerRouteWithChildren
  '/research': typeof AuthenticatedResearchRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/planner/$planId': typeof AuthenticatedPlannerPlanIdRoute
  '/research/$reportId': typeof AuthenticatedResearchReportIdRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/planner/': typeof AuthenticatedPlannerIndexRoute
  '/research/': typeof AuthenticatedResearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/planner/$planId': typeof AuthenticatedPlannerPlanIdRoute
  '/research/$reportId': typeof AuthenticatedResearchReportIdRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/planner': typeof AuthenticatedPlannerIndexRoute
  '/research': typeof AuthenticatedResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/planner': typeof AuthenticatedPlannerRouteWithChildren
  '/_authenticated/research': typeof AuthenticatedResearchRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/planner/$planId': typeof AuthenticatedPlannerPlanIdRoute
  '/_authenticated/research/$reportId': typeof AuthenticatedResearchReportIdRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/planner/': typeof AuthenticatedPlannerIndexRoute
  '/_authenticated/research/': typeof AuthenticatedResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/dashboard'
    | '/history'
    | '/planner'
    | '/research'
    | '/settings'
    | '/api/chat'
    | '/chat/$threadId'
    | '/planner/$planId'
    | '/research/$reportId'
    | '/chat/'
    | '/planner/'
    | '/research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/api/chat'
    | '/chat/$threadId'
    | '/planner/$planId'
    | '/research/$reportId'
    | '/chat'
    | '/planner'
    | '/research'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/planner'
    | '/_authenticated/research'
    | '/_authenticated/settings'
    | '/api/chat'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/planner/$planId'
    | '/_authenticated/research/$reportId'
    | '/_authenticated/chat/'
    | '/_authenticated/planner/'
    | '/_authenticated/research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/research': {
      id: '/_authenticated/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AuthenticatedResearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner': {
      id: '/_authenticated/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AuthenticatedPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/research/': {
      id: '/_authenticated/research/'
      path: '/'
      fullPath: '/research/'
      preLoaderRoute: typeof AuthenticatedResearchIndexRouteImport
      parentRoute: typeof AuthenticatedResearchRoute
    }
    '/_authenticated/planner/': {
      id: '/_authenticated/planner/'
      path: '/'
      fullPath: '/planner/'
      preLoaderRoute: typeof AuthenticatedPlannerIndexRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/research/$reportId': {
      id: '/_authenticated/research/$reportId'
      path: '/$reportId'
      fullPath: '/research/$reportId'
      preLoaderRoute: typeof AuthenticatedResearchReportIdRouteImport
      parentRoute: typeof AuthenticatedResearchRoute
    }
    '/_authenticated/planner/$planId': {
      id: '/_authenticated/planner/$planId'
      path: '/$planId'
      fullPath: '/planner/$planId'
      preLoaderRoute: typeof AuthenticatedPlannerPlanIdRouteImport
      parentRoute: typeof AuthenticatedPlannerRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedPlannerRouteChildren {
  AuthenticatedPlannerPlanIdRoute: typeof AuthenticatedPlannerPlanIdRoute
  AuthenticatedPlannerIndexRoute: typeof AuthenticatedPlannerIndexRoute
}

const AuthenticatedPlannerRouteChildren: AuthenticatedPlannerRouteChildren = {
  AuthenticatedPlannerPlanIdRoute: AuthenticatedPlannerPlanIdRoute,
  AuthenticatedPlannerIndexRoute: AuthenticatedPlannerIndexRoute,
}

const AuthenticatedPlannerRouteWithChildren =
  AuthenticatedPlannerRoute._addFileChildren(AuthenticatedPlannerRouteChildren)

interface AuthenticatedResearchRouteChildren {
  AuthenticatedResearchReportIdRoute: typeof AuthenticatedResearchReportIdRoute
  AuthenticatedResearchIndexRoute: typeof AuthenticatedResearchIndexRoute
}

const AuthenticatedResearchRouteChildren: AuthenticatedResearchRouteChildren = {
  AuthenticatedResearchReportIdRoute: AuthenticatedResearchReportIdRoute,
  AuthenticatedResearchIndexRoute: AuthenticatedResearchIndexRoute,
}

const AuthenticatedResearchRouteWithChildren =
  AuthenticatedResearchRoute._addFileChildren(
    AuthenticatedResearchRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedPlannerRoute: typeof AuthenticatedPlannerRouteWithChildren
  AuthenticatedResearchRoute: typeof AuthenticatedResearchRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedPlannerRoute: AuthenticatedPlannerRouteWithChildren,
  AuthenticatedResearchRoute: AuthenticatedResearchRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
